
logging: 
  config: classpath:logback.xml
  level: 
    root: INFO
    vcp.api.service: DEBUG
    vcp: DEBUG

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

spring:
  main:
    banner-mode: log
    allow-bean-definition-overriding: true    
  datasource:
#LOCAL    
    url: ${url:jdbc:postgresql://localhost/openshiftdb} 
    username: ${username:postgres}
    password: ${password:12345678}
    driver-class-name: org.postgresql.Driver 
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hbm2ddl:
          auto: update
